### ISSUE TITLE
Aggregation of All Markets for a certain country on the same date

### ISSUE THREAD

**Issue by ElsieZhang** [hiring-lab/remote-tracker#2]
Hi Hiring Lab Team, I am looking at your remote posting notmcats all markets dataset and found that the aggregation of each category is largely exceed 100. I also noticed that jobs like IT Operations, Software Development, Information Design & Development in the same country on the same day always have similar trend and shares. Does this mean that one job can be counted in multiple categories, which can then explain aggregation of shares of each category exceed 100?

**Comment by stham007** [comment]
Hey Elsie,

I think there is a misunderstanding of how to interpret the data. The numbers derived are from taking the total number of remote job postings in that category and dividing it by the total number of job postings in that category. It wouldn't add up to 100%. 

Best,
Shawn
